### ISSUE TITLE
App does not work with Nextcloud

### ISSUE THREAD

**Issue by simon-anderson** [pdsinterop/solid-nextcloud#71] opened 2022-04-27 03:37 UTC
The instructions tell you to copy the JSON contents of a file that doesn't exist.

**Comment by Potherca** [comment] 2022-04-28 09:35
Hi! I am sorry to hear you are having a disappointing experience with this app.

Sadly, at this point, the software is not yet stable or guaranteed to work. It is not even in beta, yet. This is reflected by the version in the app store, which is `0.0.3`, as well as the version here in the repo (v0.4.2). Both are not at version 1.0, yet.

We might have to add more distinct wording to make this clear for other future users. (I have created an issue for that: #72).

If you were expecting an easy, fully featured application, I am afraid you will have to wait some while before we reach that point.

If you are serious in trying out this application (which is still in development), there are several issues that are addressed in #66 (which is also pinned to the issue list, so users can more easily find it) and #61 which you could try. We will do our best to help you get up and running.

In either case, I am going to have to ask you to moderate your wording. I can understand your frustration, but that does not warrant an excuse for venting through bad language.

Hence, I have changed the title of this issue to something more respectful of the people who are helping to bring this application closer to v1.

- - -

<sup>Possible duplicate of: #61</sup>

**Comment by simon-anderson** [comment] 2022-04-28 12:49
Fuck off. Do the community a favour and remove this crap from the Nextcloud app store until such time as it's viable.

Regards,
S.

**Closed** 2022-04-28 16:23 UTC
